# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ad82eff3614e9715cc8a48442e4b1db010a12cf74ebb43a5e4a3dbaa2a2d3ba0a1de6db8b39fe517c4e4941c118717441c9552bc89bf3f7b21346670571174a

test:
  secret_key_base: cd261c017b90d47286e74d6b96cd8ad2ff1d90ba934ed13574766913bb3d6d7202f4daa3736ebe083231cc1ce13891a97c10b0d4c5960831d1938f5a6fd858d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
